---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-certificate
  namespace: jellyfin
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretName: jellyfin-certificate-secret
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
  dnsNames:
    - $(DOMAIN)