---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
  namespace: jellyfin
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jellyfin-config
  hostPath:
    path: /var/mnt/zfs/jellyfin/config
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
  namespace: jellyfin
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jellyfin-media
  hostPath:
    path: /var/mnt/zfs/media
    type: DirectoryOrCreate