---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  provider:
    vault:
      server: "domain"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "external-secrets-operator"
          key: "token"