---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-secrets
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cert-manager-secrets
  data:
  - secretKey: cloudflare_api_token_secret
    remoteRef:
      key: kv/Kubernetes
      property: cloudflare_api_token_secret